# Generated by Django 3.0.3 on 2020-02-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=50)),
                ('price_deal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('volume_deal', models.IntegerField()),
                ('sum_deal', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('date_deal', models.DateField()),
            ],
        ),
    ]
